import LeanCli.Daemon.Server.Core
import LeanCli.Daemon.Server.Helpers
import LeanCli.Daemon.Server.Endpoints
import LeanCli.Daemon.Server.Journal
import LeanCli.Daemon.State
import LeanCli.Cli.Commands
import LeanCli.Crypto.Hex
import LeanCli.Keystore.Tpm2Runtime
import LeanCli.RPC.Outbound
import LeanCli.RPC.Server
import LeanCli.Wallet.EoaStore

/-!
# Daemon server: `tpm.*` + `r1.*` RPC family

Local TPM2-backed R1 wallet operations. Nine methods:

  tpm.create / tpm.createSepolia       (P-256/R1 key generation)
  tpm.deploy                            (smart-account deploy on chain)
  tpm.listSepolia / tpm.listSepoliaAddresses
  tpm.signSepolia                       (raw digest signing)
  r1.sendSepolia / r1.sendEthSepolia / r1.sendRawSepolia
                                        (end-to-end send via r1SendFlow)

The `r1SendFlow` helper shells out to `ops/scripts/r1_sepolia.sh` for
calldata encoding + raw-tx assembly while keeping the PIN-bound TPM2
signature step in-process so notifications stream live to the TUI.
All chain reads pass through `RPC.Outbound.*` (policy-gated); the
produced calldata still flows through `decodeIntent → simulate →
ConfirmGate` at the TUI / SendRawFlow boundary.
-/

namespace LeanCli.Daemon.Server.TpmRpc

open LeanCli.Encoding.Json
open LeanCli.Keystore.Tpm2Runtime
open LeanCli.RPC.Server
open LeanCli.Wallet.Account
open LeanCli.Daemon.Server

private def tpm2CreateStatusText : CreateStatus → String
  | .created => "created"
  | .alreadyExists => "already exists"
  | .invalidKeyName => "invalid key name"
  | .invalidPin => s!"invalid PIN (must be at least {minPinLength} characters)"
  | .missingTpmDevice => "missing TPM device"
  | .missingTool tool => s!"missing required tool: {tool}"
  | .pinAuthFailed stderr =>
      s!"PIN auth failed\n\n{stderr}"
  | .pinDictionaryLockout stderr =>
      s!"TPM dictionary-attack lockout — wait for the lockout interval to elapse\n\n{stderr}"
  | .policyRejected => "Sepolia R1 account policy rejected"
  | .commandFailed cmd stderr =>
      s!"command failed: {cmd}\n\n{stderr}"

private def tpm2CreateReportText (report : CreateReport) : String :=
  "leanCLI TPM2 R1 wallet creation\n\n\
   Requested wallet:\n\
     - account: r1-smart (chain-agnostic; deploy selects chain)\n\
     - backend: local Linux TPM2\n\
     - curve: P-256/R1\n\
     - custody: local only; no online keystore\n\n\
   Result:\n\
     - status: " ++ tpm2CreateStatusText report.status ++ "\n\
     - key directory: " ++ report.keyDir.toString ++ "\n\
     - public key: " ++ report.publicKey.toString ++ "\n\
     - manifest: " ++ report.manifest.toString ++ "\n\n\
   Security boundary:\n\
     - created through local tpm2-tools only\n\
     - PIN is bound to the TPM key as a userwithauth value\n\
     - no seed or raw private key is generated by Lean\n\
     - TPM private blob remains wrapped for the local TPM\n\
     - wrong-PIN attempts are rate-limited by the TPM's hardware dictionary-attack protection\n"

private def signStatusText : SignStatus → String
  | .signed => "signed"
  | .invalidKeyName => "invalid key name"
  | .invalidDigest => "invalid digest: expected 32-byte hex"
  | .invalidPin => s!"invalid PIN (must be at least {minPinLength} characters)"
  | .missingKey => "missing key"
  | .missingTpmDevice => "missing TPM device"
  | .missingTool tool => s!"missing required tool: {tool}"
  | .pinAuthFailed stderr =>
      s!"PIN auth failed\n\n{stderr}"
  | .pinDictionaryLockout stderr =>
      s!"TPM dictionary-attack lockout — wait for the lockout interval to elapse\n\n{stderr}"
  | .commandFailed cmd stderr =>
      s!"command failed: {cmd}\n\n{stderr}"

private def tpm2SignReportText (report : SignReport) : String :=
  let sigLine :=
    match report.signatureHex with
    | none => ""
    | some sig => "     - signature hex: " ++ sig ++ "\n"
  "leanCLI TPM2 R1 signing\n\n\
   Requested signer:\n\
     - key name: " ++ report.keyName ++ "\n\
     - backend: local Linux TPM2\n\n\
   Result:\n\
     - status: " ++ signStatusText report.status ++ "\n\
     - key directory: " ++ report.keyDir.toString ++ "\n\
     - digest file: " ++ report.digest.toString ++ "\n\
     - signature file: " ++ report.signature.toString ++ "\n" ++ sigLine ++
  "\n\
   Security boundary:\n\
     - signing requires the TPM-bound PIN (auth value checked by the TPM)\n\
     - digest and signature stay under the local .leancli state directory\n\
     - TPM private blob remains wrapped for the local TPM\n"

private def formatKeyList : List String → String
  | [] => "No local Sepolia TPM2 keys found.\n"
  | names =>
      "Local Sepolia TPM2 keys:\n" ++
        String.join (names.map (fun name => "- " ++ name ++ "\n"))

/-- Build the chain-RPC env vars passed to every shell script we spawn.
    Anchors the user's daemon config as the single source of truth for RPC
    URLs: `SEPOLIA_RPC_URL` / `MAINNET_RPC_URL` are populated when the
    matching endpoint exists in `cfg.chainEndpoints`, and `ETH_RPC_URL`
    (the default name `cast` / `forge` look for) is bound to whichever
    chain matches the daemon's active `chainId`. We deliberately emit
    only entries that resolve — passing `none` would *unset* the var
    in the child env, which would clobber a value the user exported
    manually for some other reason. -/
private def chainScriptEnv (cfg : Config) : Array (String × Option String) :=
  let urlFor (name : String) : Option String :=
    (cfg.chainEndpoints.find? (fun (k, _) => k = name)).map (fun (_, ep) => ep.url)
  let sepoliaUrl := urlFor "sepolia"
  let mainnetUrl := urlFor "mainnet"
  let activeUrl :=
    if cfg.chainId == 11155111 then sepoliaUrl
    else if cfg.chainId == 1 then mainnetUrl
    else none
  let pairs : List (String × Option String) :=
    [ ("SEPOLIA_RPC_URL", sepoliaUrl)
    , ("MAINNET_RPC_URL", mainnetUrl)
    , ("ETH_RPC_URL",    activeUrl) ]
  pairs.foldl (init := (#[] : Array (String × Option String))) fun acc (k, v) =>
    match v with
    | some s => acc.push (k, some s)
    | none   => acc

private def runScript (cfg : Config) (args : Array String)
    (env : Array (String × Option String) := #[]) : IO (UInt32 × String) := do
  try
    let out ← IO.Process.output
      { cmd := "./ops/scripts/r1_sepolia.sh",
        args := args,
        env := chainScriptEnv cfg ++ env }
    pure (out.exitCode, out.stdout ++ out.stderr)
  catch e =>
    pure (1, e.toString ++ "\n")

/-- Like `runScript` but returns stdout and stderr separately, so the
    daemon can parse a structured first token from stdout (e.g. the
    digest hex) without having to disentangle script status chatter. -/
private def runScriptSplit (cfg : Config) (args : Array String)
    (env : Array (String × Option String) := #[]) :
    IO (UInt32 × String × String) := do
  try
    let out ← IO.Process.output
      { cmd := "./ops/scripts/r1_sepolia.sh",
        args := args,
        env := chainScriptEnv cfg ++ env }
    pure (out.exitCode, out.stdout, out.stderr)
  catch e =>
    pure (1, "", e.toString ++ "\n")

/-- Default broadcast-confirmation timeout. Overridable per-call via the
    `LEANCLI_BROADCAST_TIMEOUT_SECS` env var so the user can wait
    longer on congested networks without a rebuild. -/
private def defaultBroadcastTimeoutSecs : Nat := 90

private def broadcastTimeoutSecs : IO Nat := do
  match ← IO.getEnv "LEANCLI_BROADCAST_TIMEOUT_SECS" with
  | some s =>
      match s.toNat? with
      | some n => pure n
      | none => pure defaultBroadcastTimeoutSecs
  | none => pure defaultBroadcastTimeoutSecs

/-- Parse a `0x`-prefixed transaction hash printed by cast's --async
    output. cast prints the hex on a line by itself. -/
private def extractTxHash (stdout : String) : Option String := do
  let lines := (stdout.splitOn "\n").map (·.trimAscii.toString)
  lines.find? (fun line =>
    line.startsWith "0x" && line.length == 66 &&
      ((line.toList.drop 2).all (fun c =>
        ('0' ≤ c ∧ c ≤ '9') || ('a' ≤ c ∧ c ≤ 'f') || ('A' ≤ c ∧ c ≤ 'F'))))

/-- Parse a raw signed EIP-1559 tx hex printed by `cast mktx`. The
    command emits a single `0x02…` line (typed-2 envelope, RLP-encoded);
    we accept any 0x-prefixed even-length hex line that is unambiguously
    longer than a 32-byte hash (so we don't confuse it with an extra
    txhash line some cast builds may emit). -/
private def extractRawSignedTx (stdout : String) : Option String := do
  let lines := (stdout.splitOn "\n").map (·.trimAscii.toString)
  lines.find? (fun line =>
    line.startsWith "0x" && line.length > 66 && line.length % 2 == 0 &&
      ((line.toList.drop 2).all (fun c =>
        ('0' ≤ c ∧ c ≤ '9') || ('a' ≤ c ∧ c ≤ 'f') || ('A' ≤ c ∧ c ≤ 'F'))))

/-- Poll `eth_getTransactionReceipt` until the tx is mined or the
    timeout elapses. Emits `tx-pending` notifications every poll while
    the receipt is still null. Returns the receipt JSON on success, or
    a string error on timeout / RPC failure. -/
private partial def waitForReceipt
    (cfg : Config) (notify : LeanCli.Keystore.Tpm2Runtime.Notifier)
    (txHash : String) (deadlineMs startMs : Nat)
    (via? : Option LeanCli.RPC.Outbound.VerifyVia := none) :
    IO (Except String Json) := do
  let now ← IO.monoMsNow
  if now ≥ deadlineMs then
    pure (.error s!"timed out waiting for receipt after {(now - startMs) / 1000}s")
  else
    match ← LeanCli.RPC.Outbound.getTransactionReceipt cfg.policy cfg.rpcEndpoint txHash via? with
    | .error err => pure (.error err)
    | .ok json =>
        match json with
        | .null =>
            notify "tx-pending" (.obj #[
              ("txHash", .str txHash),
              ("elapsedSec", .num (Int.ofNat ((now - startMs) / 1000)))
            ])
            IO.sleep 5000
            waitForReceipt cfg notify txHash deadlineMs startMs via?
        | _ => pure (.ok json)

/-- End-to-end R1 send flow:
    1. shell out to `prepare-digest(-eth)` to compute the digest;
    2. natively run `signSepoliaDigest` so PIN notifications stream live;
    3. shell out to `broadcast-signed` (which uses `cast send --async`);
    4. poll `eth_getTransactionReceipt` until mined or timeout, with
       `tx-broadcasted`, `tx-pending`, `tx-mined` notifications.
    The script-side calls are still captured via `IO.Process.output`,
    but the TPM auth-value check is now in-process Lean and reaches the
    CLI in real time over the existing UDS notification channel. -/
private def r1SendFlow (cfg : Config) (state : LeanCli.Daemon.State.Shared)
    (notify : LeanCli.Keystore.Tpm2Runtime.Notifier)
    (keyName to : String) (amount : String) (mode : String)
    (pin : String)
    (data? : Option String := none) :
    IO (Except RpcError Json) := do
  let scriptEnv : Array (String × Option String) := #[("LEANCLI_TPM_KEY", some keyName)]
  -- Step 1: digest preparation. The script prints `<digest> <account> <wei>`
  -- on stdout and any `cast`/setup chatter on stderr.
  -- When `data?` is `none`, no extra arg is appended — preserving byte-identical
  -- behaviour for the value-only callers (`r1.sendSepolia`, `r1.sendEthSepolia`).
  -- When `some hex`, the script's optional `[data-hex]` 4th positional arg is
  -- forwarded to `prepare-digest(-eth)` and `broadcast-signed`.
  let dataArgs : Array String :=
    match data? with
    | some d => #[d]
    | none   => #[]
  let prepArgs : Array String :=
    if mode == "eth" then #["prepare-digest-eth", to, amount] ++ dataArgs
    else #["prepare-digest", to, amount] ++ dataArgs
  let (prepCode, prepOut, prepErr) ← runScriptSplit cfg prepArgs scriptEnv
  if prepCode != 0 then
    return .error
      { code := -32040,
        message := "r1 digest preparation failed",
        data := some (.str (prepOut ++ prepErr)) }
  let tokens := prepOut.trimAscii.toString.splitOn " " |>.filter (fun t => t.trimAscii.toString != "")
  match tokens with
  | digest :: account :: wei :: _ =>
      -- Step 2: native TPM2 sign with PIN auth value (live notifications).
      let report ← signSepoliaDigest digest pin { keyName := keyName } notify
      match report.status with
      | .signed =>
          let some sigHex := report.signatureHex
            | pure (.error
                { code := -32041,
                  message := "tpm sign returned no signature hex",
                  data := none })
          -- Step 3a: have the script ABI-encode + sign the EIP-1559
          -- envelope locally (relayer EOA pays gas) but NOT broadcast —
          -- it prints the raw signed tx hex. Append optional data hex so
          -- the signed tx carries calldata when the caller is
          -- `r1.sendRawSepolia`.
          let (bcCode, bcOut, bcErr) ← runScriptSplit cfg
            (#["broadcast-signed", sigHex, to, wei] ++ dataArgs) scriptEnv
          if bcCode != 0 then
            return .error
              { code := -32042,
                message := "r1 mktx failed",
                data := some (.str (bcOut ++ bcErr)) }
          let some rawTx := extractRawSignedTx bcOut
            | pure <| .error
                { code := -32042,
                  message := "could not parse raw signed tx from mktx output",
                  data := some (.str (bcOut ++ bcErr)) }
          -- Step 3b: broadcast through Outbound so the call lands in the
          -- daemon's network log (network monitor / audit trail). The
          -- response is the txHash string — that's the canonical hash
          -- per eth_sendRawTransaction.
          let txHashJson ← LeanCli.RPC.Outbound.sendRawTransaction
            cfg.policy cfg.rpcEndpoint rawTx
          match txHashJson with
          | .error err =>
              pure <| .error
                { code := -32020,
                  message := "chain RPC failed",
                  data := some (.str err) }
          | .ok j =>
            match asString j with
            | none =>
                pure <| .error
                  { code := -32020,
                    message := "chain RPC failed",
                    data := some (.str "eth_sendRawTransaction returned non-string result") }
            | some txHash =>
              notify "tx-broadcasted" (.obj #[
                ("txHash", .str txHash),
                ("from", .str account),
                ("to", .str to),
                ("valueWei", .str wei)
              ])
              -- Step 4: wait for receipt with periodic notifications.
              let timeoutSecs ← broadcastTimeoutSecs
              let startMs ← IO.monoMsNow
              let deadlineMs := startMs + timeoutSecs * 1000
              let via? ← colibriVia state cfg.chainId
              match ← waitForReceipt cfg notify txHash deadlineMs startMs via? with
              | .error err =>
                  let weiN := wei.toNat?.getD 0
                  let dataHexJ := data?.getD ""
                  journalRecord keyName account to txHash dataHexJ "r1.send"
                    weiN 0 cfg.chainId none (some "pending") none none
                  pure <| .ok <| .obj #[
                    ("text", .str s!"R1 send broadcast {txHash} but receipt wait failed: {err}\n"),
                    ("exitCode", .num 1),
                    ("status", .str "pending"),
                    ("txHash", .str txHash),
                    ("from", .str account),
                    ("to", .str to),
                    ("valueWei", .str wei),
                    ("error", .str err)
                  ]
              | .ok receipt =>
                  let blockNumber := (getField "blockNumber" receipt >>= asString).getD ""
                  let gasUsed := (getField "gasUsed" receipt >>= asString).getD ""
                  let effectiveGasPrice :=
                    (getField "effectiveGasPrice" receipt >>= asString).getD ""
                  let statusHex := (getField "status" receipt >>= asString).getD "0x0"
                  let success := statusHex == "0x1"
                  notify "tx-mined" (.obj #[
                    ("txHash", .str txHash),
                    ("blockNumber", .str blockNumber),
                    ("gasUsed", .str gasUsed),
                    ("effectiveGasPrice", .str effectiveGasPrice),
                    ("status", .str (if success then "success" else "revert"))
                  ])
                  let weiN := wei.toNat?.getD 0
                  let dataHexJ := data?.getD ""
                  journalRecord keyName account to txHash dataHexJ "r1.send"
                    weiN 0 cfg.chainId none
                    (some (if success then "success" else "revert"))
                    (some blockNumber) (some gasUsed)
                  let summary :=
                    s!"R1 send {txHash}\n  from: {account}\n  to: {to}\n  value: {humanEth weiN}\n  block: {humanBlock blockNumber}\n  gasUsed: {humanGas gasUsed}\n  effectiveGasPrice: {humanGwei effectiveGasPrice}\n  status: {if success then "success" else "revert"}\n"
                  pure <| .ok <| .obj #[
                    ("text", .str summary),
                    ("exitCode", .num (Int.ofNat (if success then 0 else 1))),
                    ("status", .str (if success then "success" else "revert")),
                    ("txHash", .str txHash),
                    ("from", .str account),
                    ("to", .str to),
                    ("valueWei", .str wei),
                    ("blockNumber", .str blockNumber),
                    ("gasUsed", .str gasUsed),
                    ("effectiveGasPrice", .str effectiveGasPrice),
                    ("receipt", receipt)
                  ]
      | other =>
          pure <| .error
            { code := -32043,
              message := "tpm sign failed: " ++ signStatusText other,
              data := none }
  | _ =>
      pure <| .error
        { code := -32040,
          message := "r1 digest preparation produced unexpected output",
          data := some (.str prepOut) }

/-- Handle every `tpm.*` and `r1.*` JSON-RPC method. -/
def dispatch (cfg : Config) (state : LeanCli.Daemon.State.Shared)
    (notify : LeanCli.Keystore.Tpm2Runtime.Notifier)
    (req : Request) : IO (Except RpcError Json) := do
  match req.method with
  | "tpm.create" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          match paramString req.params "pin" with
          | .error err => pure (.error err)
          | .ok pin =>
              let report ← createR1Key pin { keyName := keyName } notify
              pure <| .ok <| textResultJson (tpm2CreateReportText report) report.status.exitCode
  -- Back-compat alias kept for one release; delegates to tpm.create.
  | "tpm.createSepolia" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          match paramString req.params "pin" with
          | .error err => pure (.error err)
          | .ok pin =>
              let report ← createR1Key pin { keyName := keyName } notify
              pure <| .ok <| textResultJson (tpm2CreateReportText report) report.status.exitCode
  | "tpm.deploy" =>
      -- Params:
      --   name             : string  (R1 key slot to deploy)
      --   chain            : string  ("sepolia" today; "mainnet" not yet enabled)
      --   deployer         : optional string ("env" | "eoa"; default "env")
      --   deployerEoa      : required when deployer="eoa" — slot name
      --   deployerPassphrase : required when deployer="eoa" — slot passphrase
      -- Why: the deploy script's deployer_private_key() reads
      -- SEPOLIA_DEPLOYER_PRIVATE_KEY (or PRIVATE_KEY) from env. When
      -- deployer="eoa" we transiently inject that env var from an
      -- unlocked-on-the-fly EOA seed → BIP-32-derived secp256k1 key,
      -- so users don't have to keep a raw pk in .env.
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          match paramString req.params "chain" with
          | .error err => pure (.error err)
          | .ok chain =>
              let deployer := (getField "deployer" req.params >>= asString).getD "env"
              let deployerEnvRes : IO (Except RpcError (Array (String × Option String))) := do
                match deployer with
                | "env" =>
                    pure (.ok #[("LEANCLI_TPM_KEY", some keyName)])
                | "eoa" =>
                    match paramString req.params "deployerEoa",
                          paramString req.params "deployerPassphrase" with
                    | .ok eoaName, .ok pp =>
                        match ← LeanCli.Wallet.EoaStore.load eoaName with
                        | .error err =>
                            pure (.error
                              { code := -32050,
                                message := "deployer EOA load failed",
                                data := some (.str err) })
                        | .ok record =>
                            -- Master-KEK / already-unlocked fast path:
                            -- when `pp` is empty, prefer the in-memory
                            -- unlocked seed (set by an earlier
                            -- eoa.unlock — possibly via the master fast
                            -- path). This lets the TUI run UnlockEoaStep
                            -- before tpm.deploy and pass an empty
                            -- passphrase, instead of asking the user for
                            -- an ephemeral passphrase they don't have.
                            -- Additive: a real passphrase still runs the
                            -- per-slot KDF path below unchanged.
                            let seedRes ←
                              if pp.length == 0 then
                                match ← LeanCli.Daemon.State.getUnlocked? state eoaName with
                                | some slot => pure (.ok slot.seed)
                                | none =>
                                    pure (.error "deployer EOA is locked — unlock it first (no passphrase supplied)")
                              else
                                LeanCli.Wallet.EoaStore.unlockSeedIO record pp
                            match seedRes with
                            | .error err =>
                                pure (.error
                                  { code := -32051,
                                    message := "deployer EOA unlock failed",
                                    data := some (.str err) })
                            | .ok seed =>
                                match ← derivePrivateKeyFromSeed seed record.derivationPath with
                                | .error err =>
                                    pure (.error
                                      { code := -32052,
                                        message := "deployer EOA pk derivation failed",
                                        data := some (.str err) })
                                | .ok pk =>
                                    -- Hex.encode already prepends "0x"; do NOT
                                    -- add another one (forge rejects "0x0x…"
                                    -- with "Failed to decode private key").
                                    let pkHex := LeanCli.Crypto.Hex.encode pk
                                    pure (.ok #[
                                      ("LEANCLI_TPM_KEY", some keyName),
                                      ("SEPOLIA_DEPLOYER_PRIVATE_KEY", some pkHex),
                                      ("PRIVATE_KEY", some pkHex)
                                    ])
                    | _, _ =>
                        pure (.error
                          { code := -32602,
                            message := "deployer=\"eoa\" requires deployerEoa and deployerPassphrase" })
                | other =>
                    pure (.error
                      { code := -32602,
                        message := s!"unknown deployer: {other} (expected \"env\" or \"eoa\")" })
              match ← deployerEnvRes with
              | .error err => pure (.error err)
              | .ok scriptEnv =>
                  match chain with
                  | "sepolia" =>
                      if accepted sepoliaR1Smart then
                        let (exitCode, text) ← runScript cfg #["deploy"] scriptEnv
                        pure <| .ok <| textResultJson text exitCode
                      else
                        pure <| .ok <| textResultJson
                          "Sepolia R1 account policy rejected\n" 1
                  | "mainnet" =>
                      pure <| .ok <| textResultJson
                        "mainnet R1 deploy is not enabled yet; deploy and verify the account path on Sepolia first\n" 2
                  | other =>
                      pure <| .ok <| textResultJson
                        s!"unsupported chain: {other} (expected sepolia or mainnet)\n" 2
  | "tpm.listSepolia" =>
      let names ← listSepoliaKeys
      pure <| .ok <| textResultJson (formatKeyList names) 0
  | "tpm.listSepoliaAddresses" =>
      let names ← listSepoliaKeys
      let stateDir : System.FilePath := ".leancli/keystore/tpm2"
      let mut entries : Array Json := #[]
      for name in names do
        let addrFile := stateDir / name / "r1-account-address.txt"
        let address ←
          if ← addrFile.pathExists then
            let raw ← IO.FS.readFile addrFile
            pure raw.trimAscii.toString
          else pure ""
        entries := entries.push <| .obj #[
          ("name", .str name),
          ("address", .str address)
        ]
      pure (.ok (.arr entries))
  | "tpm.signSepolia" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          match paramString req.params "digest", paramString req.params "pin" with
          | .ok digest, .ok pin =>
              let report ← signSepoliaDigest digest pin { keyName := keyName } notify
              pure <| .ok <| textResultJson (tpm2SignReportText report) report.status.exitCode
          | _, _ => pure (.error invalidParams)
  | "r1.sendSepolia" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          match paramString req.params "to",
                paramString req.params "amountWei",
                paramString req.params "pin" with
          | .ok to, .ok amountWei, .ok pin =>
              r1SendFlow cfg state notify keyName to amountWei "wei" pin
          | _, _, _ => pure (.error invalidParams)
  | "r1.sendEthSepolia" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          match paramString req.params "to",
                paramString req.params "amountEth",
                paramString req.params "pin" with
          | .ok to, .ok amountEth, .ok pin =>
              r1SendFlow cfg state notify keyName to amountEth "eth" pin
          | _, _, _ => pure (.error invalidParams)
  | "r1.sendRawSepolia" =>
      -- Why: lets the TUI swap flow (and any future R1-side raw-tx surface)
      -- ship `{to,value,data}` through the same TPM2-backed pre-sign pipeline
      -- as `r1.sendEthSepolia`, gated by the TPM-bound PIN. The TUI already
      -- round-trips the pre-sign Confirm step before calling here.
      -- `value` accepts a JSON integer (bigint from `daemon.ts`) or a
      -- `0x`-prefixed / decimal `String`. `data` must start with `0x` and
      -- contain at least one byte; for value-only sends use `r1.sendSepolia`.
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          match paramString req.params "to",
                paramNatOrHexStr req.params "value",
                paramString req.params "data",
                paramString req.params "pin" with
          | .ok to, .ok value, .ok data, .ok pin =>
              let trimmed := data.trimAscii.toString
              if !(trimmed.startsWith "0x" || trimmed.startsWith "0X") then
                pure (.error invalidParams)
              else if trimmed.length ≤ 2 then
                -- "0x" alone is a value-only send; route via r1.sendSepolia.
                pure (.error invalidParams)
              else
                r1SendFlow cfg state notify keyName to (toString value) "wei" pin (some trimmed)
          | _, _, _, _ => pure (.error invalidParams)
  | m =>
      pure <| .error { code := -32601, message := s!"method not found: {m}", data := none }

end LeanCli.Daemon.Server.TpmRpc
