import LeanCli.Ethereum.Address
import LeanCli.Swap.Tokens

/-!
# Semantic transaction intent

A user-level "what should this transaction *do*" — sits above
`LeanCli.Ethereum.Tx` (byte-level EIP-1559 fields) and below the TUI's
form fields and the LLM's parsed JSON. Both UX surfaces produce an
`Intent`; both flow through the same encoder + decode + simulate +
confirm pipeline. One ADT, one validator, one trust boundary.

## Why a sum type, not a flat record with optional fields

Each action has different required fields. Modelling them as nullable
columns invites a class of bug where the wrong combination passes
validation (e.g. a swap with no `tokenOut`). Pattern-matching on the
constructor makes those combinations structurally impossible.

## Construction

* **Trusted path**: TUI/CLI form fields → `Intent` via a total
  constructor (see `LeanCli/Ethereum/Intent.lean` and the future
  `Tx/Trusted.lean` glue). No parsing, no LLM. Construction is total —
  if the form validates, an `Intent` exists.
* **Chat path**: untrusted LLM JSON → `Intent` via the future
  `LeanCli/LlmAgent/IntentParser.lean`, which is fallible
  (`Except String Intent`) and hard-rejects on the known model-failure
  modes documented in `memory/project_local_llm_daemon.md`.

## Invariants this type encodes structurally

* `chainId` is always present (every constructor takes it).
* Addresses are typed (`LeanCli.Ethereum.Address.Address`), not
  strings; impossible to pass an unparsed hex blob.
* Slippage floor on swaps is non-optional (`minAmountOut : Nat`). The
  encoder is expected to refuse `minAmountOut = 0`.
* `approve` amount is structured (`ApproveAmount`), not a magic
  `2^256 - 1` sentinel. The trusted path can refuse `.unlimited` at the
  UX layer; the chat-path parser can flag it separately.

Theorems about the type live in `LeanCli/Invariants/IntentTrusted.lean`
(to be added in a later slice).
-/

namespace LeanCli.Ethereum.Intent

open LeanCli.Ethereum.Address

/-- EIP-155 chain ID. `Nat` rather than `LeanCli.Swap.Tokens.ChainId`
because the intent type must accept any chain the daemon is configured
for (testnets, alt-L1s) without requiring an exhaustive enum. The
encoder + validator narrow this back to the supported set. -/
abbrev ChainId := Nat

/-- Amount in the smallest unit of the asset (wei for ETH, token base
units for ERC-20s). -/
abbrev Amount := Nat

/-- How much an `approve` permits. The `unlimited` variant exists so the
trusted path can refuse it explicitly without us comparing against a
magic `2^256 - 1` constant — and so the chat-path parser can surface it
as a distinct warning. -/
inductive ApproveAmount where
  | exact (amount : Amount)
  | unlimited
  deriving Repr, DecidableEq

/-- How confident the producer of an `Intent` is. The trusted hard-wired
path always produces `.high`. The chat path's parser sets this based on
the regex/LLM agreement and the absence of hard-reject triggers. -/
inductive Confidence where
  | high
  | medium
  | low
  | rejected
  deriving Repr, DecidableEq

/-- Kind of wallet generated by the `freshAddress` intent.

* `.eoa` — secp256k1 keypair derived from a BIP-39 mnemonic (12 or 24
  words). The mnemonic is the user's recovery path; the seed is
  persisted on disk encrypted under the master KEK (which is TPM-sealed
  at rest). Signing happens in process memory. Default.
* `.r1` — secp256r1 (P-256) keypair generated inside the TPM. The
  private key never leaves the chip; signing is hardware-bound. Used
  as an ERC-4337 R1 smart account; deployment is a separate optional
  step (the wallet can receive without deployment, but cannot send
  until deployed).
-/
inductive WalletKind where
  | eoa
  | r1
  deriving Repr, DecidableEq

/-- Render `WalletKind` as the wire tag string. -/
def WalletKind.toString : WalletKind → String
  | .eoa => "eoa"
  | .r1  => "r1"

/-- Semantic intent — what the user wants to do, before encoding to
calldata. Each constructor carries exactly the fields it needs; no
optional gunk. -/
inductive Intent where
  /-- Native (ETH) transfer. No calldata. -/
  | nativeTransfer
      (chainId : ChainId)
      (to : Address)
      (amountWei : Amount)
  /-- ERC-20 transfer. `decimals` is captured at construction time so the
  intent is self-describing — the encoder doesn't have to round-trip
  through a registry, and a corrupted registry later can't change what
  bytes get signed. -/
  | erc20Transfer
      (chainId : ChainId)
      (token : Address)
      (decimals : Nat)
      (to : Address)
      (amount : Amount)
  /-- ERC-20 `approve`. The trusted UX can refuse `.unlimited` here. -/
  | erc20Approve
      (chainId : ChainId)
      (token : Address)
      (spender : Address)
      (amount : ApproveAmount)
  /-- Uniswap V3 single-pool exact-input swap.

  * `fee` — pool fee tier (uint24 in Solidity; 100 / 500 / 3000 / 10000).
  * `minAmountOut` — slippage floor in `tokenOut` base units. The
    encoder MUST refuse `minAmountOut = 0`.
  * `deadline` — Unix seconds; encoder should refuse if in the past. -/
  | uniswapV3SwapSingle
      (chainId : ChainId)
      (tokenIn : Address)
      (tokenOut : Address)
      (amountIn : Amount)
      (fee : Nat)
      (minAmountOut : Amount)
      (recipient : Address)
      (deadline : Nat)
  /-- Aave V3 `supply`. The required pre-step `approve` is emitted as a
  separate `erc20Approve` intent — multi-step flows are composed at the
  call site, not bundled here. -/
  | aaveV3Supply
      (chainId : ChainId)
      (asset : Address)
      (amount : Amount)
      (onBehalfOf : Address)
  /-- Aave V3 `withdraw`. -/
  | aaveV3Withdraw
      (chainId : ChainId)
      (asset : Address)
      (amount : Amount)
      (recipient : Address)
  /-- Last-resort: caller-supplied calldata. Used by the manual decode
  screen and by the chat path when the model picks `emit_raw_calldata`.
  Always treated as low-confidence by the UX layer; the simulate gate
  remains the user's primary safety net here. -/
  | rawCall
      (chainId : ChainId)
      (to : Address)
      (valueWei : Amount)
      (data : ByteArray)
      (rationale : String)
  /-- Privacy Pools deposit. ETH leaves the user's EOA and enters the
  shielded pool contract. The chat-path handler in `Server.lean#chat.draft`
  routes this to `shielded.prepareDeposit` (the daemon RPC that runs the
  bridge sidecar's witness generation and returns one or more prepared
  txs). Each prepared tx still flows through `tx.simulate` + ConfirmGate
  before signing — multi-tx deposits surface as sequential confirms. -/
  | shieldedDeposit
      (chainId : ChainId)
      (amountWei : Amount)
  /-- Privacy Pools withdraw. The shielded balance is withdrawn to
  `recipient`, canonically a freshly-generated wallet (`freshAddress`)
  that has never appeared in the deposit chain — so the on-chain link
  between the source EOA and the recipient is broken. Routed to
  `shielded.prepareWithdraw` and goes through the same per-tx
  ConfirmGate pipeline as the deposit.

  `viaRelayer` controls who pays gas: `true` (the privacy-preserving
  default) routes through a relayer so `recipient` never appears as a
  gas-paying sender; `false` is self-paid, which reveals the recipient's
  ETH balance change at chain level and partially defeats the mix. -/
  | shieldedWithdraw
      (chainId : ChainId)
      (amountWei : Amount)
      (recipient : Address)
      (viaRelayer : Bool)
  /-- Railgun shield. ETH leaves the user's EOA and enters the Railgun
  shielded balance under the user's viewing/spending keys. The
  chat-path handler routes this to `shielded.railgun.prepareShield`
  (which uses the @kohaku-eth/railgun SDK over the bridge sidecar to
  generate the userOp + paymaster sponsorship and returns a single
  prepared tx). The prepared tx still flows through `tx.simulate` +
  ConfirmGate before signing.

  Distinct from `.shieldedDeposit` (which targets the 0xbow Privacy
  Pool contract) so the regex parser can route per-provider chat
  shortcuts to the right prepare RPC. Shields take minutes-to-hours
  to become spendable as the POI tree updates — the prepare RPC
  surfaces that delay in its response. -/
  | railgunShield
      (chainId : ChainId)
      (amountWei : Amount)
  /-- Railgun unshield. The shielded balance is unshielded back to a
  user-supplied `recipient`. Railgun handles relayer selection
  internally (no `viaRelayer` toggle here), so the field is absent.
  Routed to the daemon's existing `shielded.railgun.unshield` RPC
  via the standard chat.draft prepare envelope. -/
  | railgunUnshield
      (chainId : ChainId)
      (amountWei : Amount)
      (recipient : Address)
  /-- Tornado Cash deposit. ETH leaves the user's EOA and enters one
  of the four fixed-denomination mixer pools (0.1 / 1 / 10 / 100 ETH).
  The IntentParser rejects denominations outside that set; passing
  `denominationWei = 0.5 ETH` would silently mis-route to the
  wrong pool. The chat-path handler routes this to
  `shielded.tornado.prepareDeposit` (which uses snarkjs + Baby
  Jubjub Pedersen-hashing to generate the note + commitment in the
  bridge sidecar) and surfaces the resulting deposit note for the
  user to save. The prepared tx still flows through `tx.simulate` +
  ConfirmGate before signing. -/
  | tornadoDeposit
      (chainId : ChainId)
      (denominationWei : Amount)
  /-- Tornado Cash withdraw. Spends a previously-deposited note for a
  fresh recipient address. Withdrawal requires the user's saved
  deposit `note` (the secret + nullifier the bridge handed back at
  deposit time) plus current merkle-tree state from the pool's
  on-chain logs. The bridge sidecar generates the ZK proof and
  returns the `withdraw(...)` calldata.

  `note` is an opaque ASCII string (canonical form
  `tornado-note-<chain>-<denomination>-<base58>`). Treated as a
  secret — the canonical render elides the middle so screenshots
  don't leak the spending key. -/
  | tornadoWithdraw
      (chainId : ChainId)
      (denominationWei : Amount)
      (recipient : Address)
      (note : String)
  /-- Read-only listing of outgoing ERC-20 allowances for `wallet` (or
  the default wallet when omitted). The chat-path handler walks
  `chain.scanTransfers` for `Approval` events over a configurable
  block window and returns `[{token, spender, amount, lastSeenBlock}]`.
  No signing path; the response is rendered directly in the TUI. -/
  | approvalsAudit
      (chainId : ChainId)
      (wallet : Option Address)
  /-- ENS `register` — second leg of the commit/reveal flow. The chat
  path drafts this AFTER the user has already paid for the corresponding
  `commit(commitment)` and the commit-age gate (~60s on mainnet) has
  elapsed. The wallet is responsible for recomputing the same commitment
  the user committed to; the encoder pulls the persisted `secret` and
  resolver / data fields from the wallet's local registration state.

  * `name` — bare label (no `.eth` suffix). Encoder validates length
    against `ETHRegistrarController.minCommitmentAge` rules.
  * `durationSeconds` — registration period. The encoder MUST reject
    durations < the controller's `minRegistrationDuration`.
  * `owner` — address the name is registered to.

  The other `register(...)` arguments (`secret`, `resolver`, `data`,
  `reverseRecord`, `ownerControlledFuses`) live in the wallet's
  registration-state record and are not part of the `Intent` because
  they're not chosen by the user inline — they're fixed once at
  commit time. -/
  | ensRegister
      (chainId : ChainId)
      (name : String)
      (owner : Address)
      (durationSeconds : Amount)
  /-- ENS `renew` — one-shot, no commit phase. Pays the renewal fee to
  extend the name's registration. -/
  | ensRenew
      (chainId : ChainId)
      (name : String)
      (durationSeconds : Amount)
  /-- ENS `setAddr` on the resolver — point an ENS name's primary
  address at `addr`. The encoder hashes the name to a `bytes32 node`;
  the daemon's ENS namehash cache (see `Daemon/EnsNames.lean`) gets a
  fresh `(namehash, name)` entry so future decode-time renderings of
  this node are human-readable. -/
  | ensSetAddr
      (chainId : ChainId)
      (name : String)
      (addr : Address)
  /-- ENS `setName` on the resolver — set the reverse record so the
  caller's address renders as `name` in name-aware UIs. NB: this binds
  the reverse record for the CALLER, not for `name`'s owner; the
  resolver checks ownership of `name` before accepting. -/
  | ensSetName
      (chainId : ChainId)
      (name : String)
      (newName : String)
  /-- Lido `stake` — deposit native ETH into the Lido staking
  contract, receive stETH 1:1 (modulo rounding). Encoder pulls the
  Lido stETH contract address from `KnownProtocols`. The chat path
  shortcut "stake X ETH" / "stake X ETH via lido" routes here.

  `referral` is optional — empty 20-byte address means "no referral",
  which is what most users want and the encoder default. -/
  | lidoStake
      (chainId : ChainId)
      (amountWei : Amount)
  /-- Liquity V2 `openTrove` — borrow BOLD against a collateral
  branch. Recipient defaults to `owner`. Annual interest rate is in
  Liquity's 1e18-scaled units; the encoder validates against the
  branch's `minAnnualInterestRate`.

  `branch` selects the collateral (ETH/WETH, wstETH, rETH); the
  encoder picks the branch's `BorrowerOperations` from
  `KnownProtocols`. -/
  | liquityOpenTrove
      (chainId : ChainId)
      (branch : String)
      (owner : Address)
      (collateralAmount : Amount)
      (boldAmount : Amount)
      (annualInterestRate : Amount)
  /-- Liquity V2 `closeTrove`. The trove ID is `(owner, ownerIndex)`
  packed at encode time. -/
  | liquityCloseTrove
      (chainId : ChainId)
      (branch : String)
      (owner : Address)
      (ownerIndex : Amount)
  /-- Generic protocol `claim` — claims rewards / surplus collateral
  from `protocol`. The encoder fans out by `protocol` slug to the
  right ABI (`claimCollateral()` on Liquity V2 ActivePool,
  `claimRewards(...)` on Aave V3 incentives controller, etc.). -/
  | protocolClaim
      (chainId : ChainId)
      (protocol : String)
  /-- Generate a new local wallet. **Not a chain action** — `chainId` is
  recorded only as request context (some R1 deployment flows are
  chain-specific, and we may surface the chain in the wallet's label).
  No on-chain interaction happens here; an active send from the new
  address later flows through the usual signing pipeline.

  * `kind` — defaults to `.eoa` (BIP-39 mnemonic + software signing).
    `.r1` is the TPM-hardware-key opt-in.
  * `label` — local-only nickname. The parser strips PII patterns
    before accepting (see IntentParser).
  * `deployImmediately` — meaningful only for `.r1`; ignored for
    `.eoa`. Default `false`: R1 wallets can receive without being
    deployed, deployment is needed only before the first outbound tx. -/
  | freshAddress
      (chainId : ChainId)
      (kind : WalletKind)
      (label : Option String)
      (deployImmediately : Bool)

/-- The chain an intent applies to. -/
def Intent.chainId : Intent → ChainId
  | .nativeTransfer cid _ _              => cid
  | .erc20Transfer  cid _ _ _ _          => cid
  | .erc20Approve   cid _ _ _            => cid
  | .uniswapV3SwapSingle cid _ _ _ _ _ _ _ => cid
  | .aaveV3Supply   cid _ _ _            => cid
  | .aaveV3Withdraw cid _ _ _            => cid
  | .rawCall        cid _ _ _ _          => cid
  | .shieldedDeposit  cid _              => cid
  | .shieldedWithdraw cid _ _ _          => cid
  | .railgunShield    cid _              => cid
  | .railgunUnshield  cid _ _            => cid
  | .tornadoDeposit   cid _              => cid
  | .tornadoWithdraw  cid _ _ _          => cid
  | .approvalsAudit   cid _              => cid
  | .ensRegister      cid _ _ _          => cid
  | .ensRenew         cid _ _            => cid
  | .ensSetAddr       cid _ _            => cid
  | .ensSetName       cid _ _            => cid
  | .lidoStake        cid _              => cid
  | .liquityOpenTrove cid _ _ _ _ _      => cid
  | .liquityCloseTrove cid _ _ _         => cid
  | .protocolClaim    cid _              => cid
  | .freshAddress     cid _ _ _          => cid

/-- Coarse action category. Used by the regex parser (which hasn't
resolved tokens / addresses yet) and by the UI for routing to the right
confirm-screen layout. -/
inductive Action where
  | nativeTransfer
  | erc20Transfer
  | erc20Approve
  | swap
  | aaveSupply
  | aaveWithdraw
  | aaveBorrow
  | aaveRepay
  | wrap
  | unwrap
  | bridge
  | rawCall
  -- Privacy / hygiene / wallet-mgmt actions. Wire tags are dot-
  -- namespaced (`shielded.deposit`, `address.fresh`, etc.) — see
  -- `Action.toString`. The original camelCase tags are retained for
  -- the actions above to avoid breaking already-shipped skill bodies
  -- and the chat.draft picker.
  | shieldedDeposit
  | shieldedWithdraw
  -- Provider-specific shield variants. `.shieldedDeposit/Withdraw`
  -- remain bound to the 0xbow Privacy Pool surface (the canonical
  -- `shield <amount> <asset>` chat shortcut). The Railgun chat
  -- shortcut routes here so the prepare-envelope picks the Railgun
  -- daemon RPC instead of the Privacy Pool one.
  | railgunShield
  | railgunUnshield
  -- Tornado Cash variants. Fixed-denomination mixer; chat shortcut
  -- routes via `shielded.tornado.prepare{Deposit,Withdraw}`. The
  -- sidecar owns Pedersen hashing + ZK proof generation; the Lean
  -- core only validates denominations + surfaces the result through
  -- the normal ConfirmGate pipeline.
  | tornadoDeposit
  | tornadoWithdraw
  | approvalsAudit
  -- ENS chat-side actions. `ensRegister` is the second-leg-of-
  -- commit/reveal `register(...)` call; the prior `commit(...)`
  -- transaction is orchestrated by the skill card, not modelled as
  -- its own Intent variant — `commit` produces no user-visible state
  -- change beyond the commitment hash, and the user signs both txs
  -- through the same ConfirmGate path with the skill card providing
  -- the timing copy in between.
  | ensRegister
  | ensRenew
  -- ENS resolver actions (set the bytes32 node's record). These live
  -- next to register/renew because the chat shortcuts share the same
  -- ".eth" prefix recognition.
  | ensSetAddr
  | ensSetName
  -- Liquity V2 explicit trove verbs. Distinct from .aaveSupply /
  -- .aaveWithdraw because the encoder needs to pick the branch's
  -- BorrowerOperations and form openTrove/closeTrove args (which are
  -- structurally different — opens carry interest rate + dual amounts).
  | liquityOpenTrove
  | liquityCloseTrove
  -- ERC-4626 / fxUSD mint+redeem. The bare verbs route through the
  -- protocol field so the encoder picks the right contract.
  | protocolMint
  | protocolRedeem
  -- Generic claim — protocol-keyed inside the matcher; encoder
  -- dispatches to claimCollateral / claimRewards / etc.
  | protocolClaim
  -- Staking (Lido today; LST extensions later).
  | stake
  | unstake
  | freshAddress
  | unknown
  deriving Repr, DecidableEq

/-- The regex parser's structured output before it has been completed by
the LLM (chat path) or before it has been validated for the trusted
path. The LLM receives this as a *seed* — not as ground truth.

* `fields` carries the extracted attribute strings indexed by attribute
  name. Canonical keys: `"verb"`, `"amount"`, `"asset"`, `"to"`,
  `"protocol"`, `"slippage"`, `"chain"`, `"feeTier"`, `"deadline"`.
* `unresolved` is human-readable reasons the parser couldn't fully
  complete the intent — e.g., `"asset 'XYZ' not in known-tokens
  registry"`, `"recipient 'vitalik.eth' needs ENS resolution"`.
* `confidence` records what the parser thinks of its own output;
  `.rejected` means "this prompt doesn't look like a transaction at
  all", which still passes through to the LLM in case the user wrote
  something the regex missed.
-/
structure RegexDraft where
  action     : Action
  fields     : List (String × String)
  unresolved : List String
  confidence : Confidence
  deriving Repr

/-- An empty draft — every field unset, `Action.unknown`, rejected.
The starting point the parser builds up from. -/
def RegexDraft.empty : RegexDraft :=
  { action := .unknown
    fields := []
    unresolved := []
    confidence := .rejected }

/-- Look up an extracted field by canonical name. -/
def RegexDraft.field? (d : RegexDraft) (key : String) : Option String :=
  (d.fields.find? (fun (k, _) => k = key)).map Prod.snd

/-- Set / overwrite a field. Used by the parser as it builds the draft. -/
def RegexDraft.setField (d : RegexDraft) (key value : String) : RegexDraft :=
  { d with fields := (key, value) :: d.fields.filter (fun (k, _) => k ≠ key) }

/-- Add an unresolved-reason note. -/
def RegexDraft.note (d : RegexDraft) (reason : String) : RegexDraft :=
  { d with unresolved := reason :: d.unresolved }

/-- Render `Action` as its canonical tag string. The original transfer/
swap/aave/wrap variants stay in camelCase for backward compat; the new
privacy/hygiene/wallet variants use dot-namespaced tags so the
skill-picker can keep them grouped (`shielded.*`, `approvals.*`,
`address.*`). -/
def Action.toString : Action → String
  | .nativeTransfer    => "nativeTransfer"
  | .erc20Transfer     => "erc20Transfer"
  | .erc20Approve      => "erc20Approve"
  | .swap              => "swap"
  | .aaveSupply        => "aaveSupply"
  | .aaveWithdraw      => "aaveWithdraw"
  | .aaveBorrow        => "aaveBorrow"
  | .aaveRepay         => "aaveRepay"
  | .wrap              => "wrap"
  | .unwrap            => "unwrap"
  | .bridge            => "bridge"
  | .rawCall           => "rawCall"
  | .shieldedDeposit   => "shielded.deposit"
  | .shieldedWithdraw  => "shielded.withdraw"
  | .railgunShield     => "shielded.railgun.shield"
  | .railgunUnshield   => "shielded.railgun.unshield"
  | .tornadoDeposit    => "shielded.tornado.deposit"
  | .tornadoWithdraw   => "shielded.tornado.withdraw"
  | .approvalsAudit    => "approvals.audit"
  | .ensRegister       => "ens.register"
  | .ensRenew          => "ens.renew"
  | .ensSetAddr        => "ens.setAddr"
  | .ensSetName        => "ens.setName"
  | .liquityOpenTrove  => "liquity.openTrove"
  | .liquityCloseTrove => "liquity.closeTrove"
  | .protocolMint      => "protocol.mint"
  | .protocolRedeem    => "protocol.redeem"
  | .protocolClaim     => "protocol.claim"
  | .stake             => "stake"
  | .unstake           => "unstake"
  | .freshAddress      => "address.fresh"
  | .unknown           => "unknown"

/-! ## Wire-tag round-trip examples

Compiler-checked anchors for the wire-format strings. If anyone renames
a variant or changes its on-the-wire tag, these `native_decide`-checked
examples break the build before the daemon ever sees a real prompt —
matching the project convention in `Util/Units.lean`. -/

example : Action.toString .nativeTransfer    = "nativeTransfer"     := by native_decide
example : Action.toString .shieldedDeposit   = "shielded.deposit"          := by native_decide
example : Action.toString .shieldedWithdraw  = "shielded.withdraw"         := by native_decide
example : Action.toString .railgunShield     = "shielded.railgun.shield"   := by native_decide
example : Action.toString .railgunUnshield   = "shielded.railgun.unshield" := by native_decide
example : Action.toString .tornadoDeposit    = "shielded.tornado.deposit"  := by native_decide
example : Action.toString .tornadoWithdraw   = "shielded.tornado.withdraw" := by native_decide
example : Action.toString .approvalsAudit    = "approvals.audit"            := by native_decide
example : Action.toString .ensRegister       = "ens.register"               := by native_decide
example : Action.toString .ensRenew          = "ens.renew"                  := by native_decide
example : Action.toString .ensSetAddr        = "ens.setAddr"                := by native_decide
example : Action.toString .ensSetName        = "ens.setName"                := by native_decide
example : Action.toString .liquityOpenTrove  = "liquity.openTrove"          := by native_decide
example : Action.toString .liquityCloseTrove = "liquity.closeTrove"         := by native_decide
example : Action.toString .protocolMint      = "protocol.mint"              := by native_decide
example : Action.toString .protocolRedeem    = "protocol.redeem"            := by native_decide
example : Action.toString .protocolClaim     = "protocol.claim"             := by native_decide
example : Action.toString .stake             = "stake"                      := by native_decide
example : Action.toString .unstake           = "unstake"                    := by native_decide
example : Action.toString .freshAddress      = "address.fresh"              := by native_decide
example : WalletKind.toString .eoa           = "eoa"                := by native_decide
example : WalletKind.toString .r1            = "r1"                 := by native_decide

/-- Render `Confidence` as a tag string. -/
def Confidence.toString : Confidence → String
  | .high     => "high"
  | .medium   => "medium"
  | .low      => "low"
  | .rejected => "rejected"

end LeanCli.Ethereum.Intent
